# Generated by Django 5.1.5 on 2025-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
